import sys
from pathlib import Path
import requests

# Add project root to python path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from features.postgrest import create_restaurant, get_client

def test_workflow():
    print("--- Testing PostgREST API ---")
    
    # 1. Test GET
    print("\n1. Fetching Restaurants...")
    client = get_client()
    res = client.table("restaurants").select("name, cuisine").limit(3).execute()
    print(res.data)

    # 2. Test Validation (Should Fail)
    print("\n2. Testing Validation (Expected Failure)...")
    try:
        create_restaurant({
            "name": "Bad Data",
            "rating": 10.0 # Invalid rating > 5
        })
    except Exception as e:
        print(f"Caught expected validation error: {e}")

    # 3. Test Create (Should Succeed)
    print("\n3. Creating New Restaurant...")
    new_rest = {
        "name": "Python Pizza",
        "address": {"street": "123 Code Ln", "city": "Tech City", "zip": "90210"},
        "cuisine": "Italian",
        "hours": {"mon": "10:00-22:00", "tue": "10:00-22:00"},
        "rating": 4.5,
        "review_count": 0,
        "description": "The best pizza generated by code."
    }
    try:
        res = create_restaurant(new_rest)
        print(f"Created: {res.data[0]['name']}")
    except Exception as e:
        print(f"Creation failed: {e}")

if __name__ == "__main__":
    test_workflow()